---
title: "Fit MOSM GP to toy example"
format: 
  html:
    embed-resources: true
---

Fit MOSK model with $\phi_{ij} = 0$ and $\Sigma_1$, $\Sigma_2 = 0.02$.

```{r}
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(cmdstanr)
library(posterior)
library(bayesplot)
library(readr)

register_knitr_engine(override = FALSE)

theme_set(theme_bw())
color_scheme_set("viridis") # bayesplot

EXECUTE_SAMPLING <- FALSE
SEED <- round(runif(n = 1, 0, 999))
SEED 
```

# Data



$$f_1 \sim \mathcal{N}(2.0 \sin(2\pi(0.7)[t - 0.0] + 0.0), 0.25^2)$$
$$f_2 \sim \mathcal{N}(2.0 \sin(2\pi (0.7)[t - 0.4] + 0.0), 0.25^2)$$


```{r}
D <- 2
input_df <- read_csv("mcar_sinusoid.csv")

ns <- table(input_df$d)
ns
```

```{r}
input_df |> 
  ggplot() +
  aes(x = t, y = y) +
  geom_linerange(aes(ymax = y + y_se, ymin = y - y_se), colour = "black") +
  geom_vline(xintercept = 0, linetype = "dotted") +
  geom_point() +
  facet_grid(rows = vars(d))
```

## Target locations

```{r}
n_cycles <- 5
frequency <- 0.7

n_star <- 100 # in each band
N_star <- n_star * D
ns_star = rep(n_star, D)

star_df <- data.frame(
  t_star = rep(seq(from = 0, to = n_cycles/frequency, length.out = n_star), D),
  d_star = as.integer(rep(1:D, each = n_star))
)
```

# Model Fitting

```{r}
mosmgp_nophi_fixedSigma_stan <- cmdstan_model(here("stan", "moskgp-nophi-fixedSigma.stan"))
```

```{r}
SEED
```

## Sampling

```{r}
data_list <- list(
  D = D,
  N = NROW(input_df),
  ns = ns,
  d = input_df$d,
  x = input_df$t,
  y = input_df$y,
  y_se = input_df$y_se,
  N_star = N_star,
  ns_star = ns_star,
  d_star = star_df$d_star,
  x_star = star_df$t_star
)
```

```{r}
format(start_time <- Sys.time())
```

```{r}
if (EXECUTE_SAMPLING) {
  
  output <- mosmgp_nophi_fixedSigma_stan$sample(
    data = data_list,
    seed = SEED,
    chains = 6,
    parallel_chains = 6,
    iter_warmup = 500,
    iter_sampling = 1000,
    refresh = 100,
    show_exceptions = FALSE,
    show_messages = TRUE
  )
  
  output$save_object(here("RDS", "mosk_toy_sinusoid_nophi_fixedSigma.RDS"))
  
} else {
  output <- readRDS(here("RDS", "mosk_toy_sinusoid_nophi_fixedSigma.RDS"))
}
```

```{r}
format(finish_time <- Sys.time())
difftime(finish_time, start_time)  
```

# Results

```{r}
vars <- c("w", "mu", "theta", "deltaTheta")
output$summary(variables = vars, 
               posterior::default_convergence_measures())
```

```{r}
output_draws_df <- output$draws(variables = vars, format = "df") |> 
  subset_draws(chain = 3) 

output_draws_df |> 
  summary(posterior::default_convergence_measures())
```

```{r}
output_draws_df |> mcmc_trace()
```

## Hyperparameter Posteriors

```{r}
mcmc_hist(output_draws_df, facet_args = list(ncol = 4))
```

```{r}
mcmc_dens(output_draws_df, facet_args = list(ncol = 4))
```

```{r}
# Function estimates the mode of a sample
estimate_mode <- function(x) {
  d <- density(x, n = 2^10)
  d$x[which.max(d$y)]
}

output_draws_df |> 
  summary(
    mode = ~ estimate_mode(.),
    mean,
    sd = posterior::sd,
    median,
    quantiles = ~ quantile2(., probs = c(0.16, 0.84))
  )
```

```{r}
output_draws_df |> 
  select(.draw, starts_with("w")) |> 
  pivot_longer(2:3) |> 
  drop_na(value) |> 
  ggplot() +
  aes(x = value) +
  geom_histogram() +
  facet_wrap(vars(name), scales = "free_y")
```

```{r}
output_draws_df |> 
  select(.draw, starts_with("mu")) |> 
  pivot_longer(2:3) |> 
  drop_na(value) |> 
  ggplot() +
  aes(x = value) +
  geom_histogram() +
  facet_wrap(vars(name), scales = "free")
```

```{r}
output_draws_df |> 
  select(.draw, starts_with("theta")) |> 
  pivot_longer(2:3) |> 
  drop_na(value) |> 
  ggplot() +
  aes(x = value) +
  geom_histogram() +
  facet_wrap(vars(name), scales = "free_y")
```

```{r}
output_draws_df |> 
  mcmc_pairs(pars = c("w[1]", "w[2]"), off_diag_fun = "hex")
```


```{r}
output_draws_df |> 
  mcmc_pairs(pars = c("theta[1]", "theta[2]"), off_diag_fun = "hex")
```

```{r}
output_draws_df |> 
  mcmc_pairs(pars = c("mu[1]", "mu[2]"), off_diag_fun = "hex")
```

```{r}
output_draws_df |> 
  mcmc_pairs(pars = c("theta[1]", "theta[2]"), off_diag_fun = "hex")
```

## Posterior Predictive samples

```{r}
set.seed(SEED)
post_pred_samples_wide <- output$draws(variables = "f_star", format = "df") |> 
  as.data.frame() |> 
  select(sample = .draw, .chain, starts_with("f_star")) |> 
  arrange(sample) 

post_pred_samples <- post_pred_samples_wide |> 
  pivot_longer(starts_with("f_star"), 
               names_to = "index", 
               names_pattern = "([0-9]+)") |> 
  cbind(t = star_df$t_star,
        d = factor(star_df$d_star))
```

```{r}
post_pred_samples |> 
  ggplot() +
  aes(x = t, y = value, colour = d, group = sample) +
  geom_line(alpha = 0.05) +
  facet_grid(rows = vars(d)) +
  geom_point(data = input_df, mapping = aes(x = t, y = y, group = d), colour = "black", size = 0.5) +
  labs(y = "y", title = paste0("Posterior predictive samples (seed=", SEED,")")) +
  theme(legend.position = "none") 
```

```{r}
valid_postpred_sample_ids <- post_pred_samples |> 
  filter(!is.na(value)) |> 
  distinct(sample)
valid_postpred_sample_ids
```

```{r}
str(output_draws_df)
```

```{r}
summary(output_draws_df)
```

Recovered posterior estimates seem identical to experiments where $\Sigma_i$ was not fixed to particular value.

```{r}
output_draws_df |> 
  pivot_longer(cols = c(`theta[1]`, `theta[2]`), names_to = "Parameter") |> 
  ggplot() +
  aes(x = value, fill = Parameter) +
  geom_histogram(position = "identity", bins = 50, alpha = 0.5)
```

```{r}
median(output_draws_df$`theta[1]`) - median(output_draws_df$`theta[2]`)
```

```{r}
output_draws_df |> 
  ggplot() +
  aes(x = deltaTheta) +
  geom_histogram(bins = 30) +
  geom_vline(xintercept = median(output_draws_df$deltaTheta), colour = "red")
```

```{r}
quantile(output_draws_df$deltaTheta)
```
